    <div class="row login-logo">
        <div class="col-xs-4  col-sm-4 col-md-1 nav-link" style="padding: 0.3rem"></div>
        <div class="col-xs-4  col-sm-4 col-md-1 nav-link" style="padding: 0.3rem"><div  ><button class="btn btn-primary  btn-block waves-effect waves-light"   onclick="switching(this.value);"  type="button" id="page1-button" value="page1">Case Info &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</button></div></div>
        <div class="col-xs-4  col-sm-4 col-md-1 nav-link" style="padding: 0.3rem"><div  ><button class="btn btn-primary  btn-block waves-effect waves-light"   onclick="switching(this.value);"  id="page2-button" value="page2" disabled="" type="button">Login
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</button></div></div>
        <div class="col-xs-4  col-sm-4 col-md-1 nav-link" style="padding: 0.3rem"><div  ><button class="btn btn-primary  btn-block waves-effect waves-light"   onclick="switching(this.value);"  id="page3-button" value="page3" disabled="" type="button">Case Information
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</button></div></div>
        <div class="col-xs-4  col-sm-4 col-md-1 nav-link" style="padding: 0.3rem"><div  ><button class="btn btn-primary  btn-block waves-effect waves-light"   onclick="switching(this.value);"  id="page4-button" value="page4" disabled="" type="button">House Hold Details</button></div></div>
        <div class="col-xs-4  col-sm-4 col-md-1 nav-link" style="padding: 0.3rem"><div  ><button class="btn btn-primary  btn-block waves-effect waves-light"   onclick="switching(this.value);"  id="page5-button" value="page5" disabled="" type="button">Countable Assets
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</button></div></div>
        <div class="col-xs-4  col-sm-4 col-md-1 nav-link" style="padding: 0.3rem"><div  ><button class="btn btn-primary  btn-block waves-effect waves-light"   onclick="switching(this.value);"  id="page6-button" value="page6" disabled="" type="button">Deductable Liabilites
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</button></div></div>
        <div class="col-xs-4  col-sm-4 col-md-1 nav-link" style="padding: 0.3rem"><div  ><button class="btn btn-primary  btn-block waves-effect waves-light"   onclick="switching(this.value);"  id="page7-button" value="page7" disabled="" type="button">Net Countable Assets</button></div></div>

        <div class="col-xs-4  col-sm-4 col-md-1 nav-link" style="padding: 0.3rem"><div  ><button class="btn btn-primary  btn-block waves-effect waves-light"   onclick="switching(this.value);"  id="page8-button" value="page8" disabled="" type="button">Field Officer Remarks</button></div></div>
        <div class="col-xs-4  col-sm-4 col-md-1 nav-link" style="padding: 0.3rem"><div  ><button class="btn btn-primary  btn-block waves-effect waves-light"   onclick="switching(this.value);"  id="page9-button" value="page9" disabled="" type="button">Business Tab
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</button></div></div>
    </div>